- if: branch = master
  language: node_js
  node_js:
    - "6"
  addons:
    chrome: stable
  before_script:
    - npm install
  script:
    - gulp all
    - npm test
  after_success:
    - ./node_modules/.bin/codecov  -f test-output/coverage/json/coverage-final.json
  sudo: required


- if: branch = angularIvy
  language: node_js
  node_js:
    - "12"
  addons:
    chrome: stable
  before_script:
    - npm install -g @angular/cli@9.0.7
    - npm install
  script:
    - npm run test-lib
  after_success:
    - ./node_modules/.bin/codecov  -f test-output/mydatepicker/coverage-final.json
  sudo: required
  